version: '3.8'

services:
  mt4:
    build: ../..
    image: mt4-docker:latest
    container_name: mt4-terminal
    volumes:
      - ./../../MQL4:/mt4/MQL4
      - ./../../logs:/mt4/logs
      - mt4-data:/mt4/data
    environment:
      - MT4_LOGIN=${MT4_LOGIN}
      - MT4_PASSWORD=${MT4_PASSWORD}
      - MT4_SERVER=${MT4_SERVER}
    networks:
      - mt4-network

  zmq-bridge:
    image: python:3.9-slim
    container_name: zmq-bridge
    working_dir: /app
    volumes:
      - ./../../services/zeromq_bridge:/app
      - ./market_data.csv:/app/market_data.csv
      - mt4-data:/mt4-data
    command: |
      bash -c "
        pip install pyzmq &&
        python zmq_bridge.py
      "
    ports:
      - "5556:5556"  # ZeroMQ publisher port
    networks:
      - mt4-network
    depends_on:
      - mt4

  zmq-monitor:
    image: python:3.9-slim
    container_name: zmq-monitor
    working_dir: /app
    volumes:
      - ./clients/python:/app
    command: |
      bash -c "
        pip install pyzmq &&
        python zmq_market_client.py
      "
    networks:
      - mt4-network
    depends_on:
      - zmq-bridge

volumes:
  mt4-data:

networks:
  mt4-network:
    driver: bridge