apiVersion: v1
kind: ConfigMap
metadata:
  name: mt4-config
  namespace: mt4-trading
  labels:
    app.kubernetes.io/name: mt4-config
    app.kubernetes.io/part-of: mt4-trading-system
data:
  # MT4 Configuration
  MT4_SERVER: "demo.metaquotes.net:443"
  MT4_TIMEZONE: "UTC"
  
  # ZeroMQ Configuration
  ZMQ_PUB_PORT: "5556"
  ZMQ_SUB_PORT: "5557"
  
  # API Configuration
  API_PORT: "5000"
  FLASK_ENV: "production"
  
  # WebSocket Configuration
  WS_PORT: "8765"
  HEARTBEAT_INTERVAL: "30"
  
  # Redis Configuration
  REDIS_PORT: "6379"
  
  # Monitoring Configuration
  PROMETHEUS_PORT: "9090"
  GRAFANA_PORT: "3000"
  
  # Elasticsearch Configuration
  ELASTICSEARCH_PORT: "9200"
  KIBANA_PORT: "5601"
  
  # Nginx configuration for ingress
  nginx.conf: |
    upstream mt4_api {
        server mt4-api-service:5000;
    }
    
    upstream mt4_websocket {
        server mt4-websocket-service:8765;
    }
    
    server {
        listen 80;
        server_name api.mt4.example.com;
        
        location / {
            proxy_pass http://mt4_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
    
    server {
        listen 80;
        server_name ws.mt4.example.com;
        
        location / {
            proxy_pass http://mt4_websocket;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mt4-scripts
  namespace: mt4-trading
  labels:
    app.kubernetes.io/name: mt4-scripts
    app.kubernetes.io/part-of: mt4-trading-system
data:
  health-check.sh: |
    #!/bin/bash
    # Health check script for MT4
    
    # Check if MT4 terminal is running
    if pgrep -x "terminal.exe" > /dev/null; then
        echo "MT4 terminal is running"
    else
        echo "MT4 terminal is not running"
        exit 1
    fi
    
    # Check if EA is loaded
    if grep -q "MT4ZMQBridge" /mt4/MQL4/Logs/$(date +%Y%m%d).log; then
        echo "EA is loaded"
    else
        echo "EA is not loaded"
        exit 1
    fi
    
    exit 0
  
  init-mt4.sh: |
    #!/bin/bash
    # Initialize MT4 terminal
    
    echo "Initializing MT4 terminal..."
    
    # Copy configuration files
    cp /config/server.ini /mt4/config/
    
    # Ensure directories exist
    mkdir -p /mt4/MQL4/Experts
    mkdir -p /mt4/MQL4/Libraries
    mkdir -p /mt4/MQL4/Logs
    
    # Copy EA and DLL
    cp /app/MT4ZMQBridge.ex4 /mt4/MQL4/Experts/
    cp /app/mt4zmq.dll /mt4/MQL4/Libraries/
    
    echo "MT4 initialization complete"