apiVersion: v1
kind: Secret
metadata:
  name: mt4-secrets
  namespace: mt4-trading
  labels:
    app.kubernetes.io/name: mt4-secrets
    app.kubernetes.io/part-of: mt4-trading-system
type: Opaque
stringData:
  # MT4 Credentials (base64 encoded in real deployment)
  MT4_LOGIN: "demo_account"
  MT4_PASSWORD: "demo_password"
  
  # JWT Secret for API/WebSocket authentication
  JWT_SECRET: "your-secret-key-change-in-production"
  
  # Admin token for API management
  ADMIN_TOKEN: "secret_admin_token_change_in_production"
  
  # Database passwords
  REDIS_PASSWORD: "redis_password_change_in_production"
  ELASTICSEARCH_PASSWORD: "elastic_password_change_in_production"
  
  # ZeroMQ CURVE keys (generate new ones for production)
  ZMQ_SERVER_SECRET_KEY: "rq:rM>}U?@Lns47E1%kR.o@n%FcmmsL/@{H8]yf7"
  ZMQ_SERVER_PUBLIC_KEY: "Yne@$w-vo<fVvi]a<NY6T1ed:M$fCG*[IaLV{hID"

---
apiVersion: v1
kind: Secret
metadata:
  name: mt4-tls
  namespace: mt4-trading
  labels:
    app.kubernetes.io/name: mt4-tls
    app.kubernetes.io/part-of: mt4-trading-system
type: kubernetes.io/tls
data:
  # TLS certificates for HTTPS (replace with real certificates)
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi4uLgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t